spring:
  application:
    name: cz-ai-agent
  ai:
    dashscope:
      api-key: sk-ws-H.EIRELRX.nuVr.MEUCIG6HbE2Y-r0DgDhvzuBd7FDINc7SUygrp3WiI5G_LrvTAiEAqkZb2DWxaxMUAyGtIs_t-LO2Z8w1ZYb3hu8QyX_sVeM
      chat:
        options:
          model: qwen-plus

