spring:
  application:
    name: cz-ai-agent
  ai:
    dashscope:
      api-key: sk-ws-H.EIRELRX.nuVr.MEUCIG6HbE2Y-r0DgDhvzuBd7FDINc7SUygrp3WiI5G_LrvTAiEAqkZb2DWxaxMUAyGtIs_t-LO2Z8w1ZYb3hu8QyX_sVeM
      chat:
        options:
          model: qwen-max
  # 邮件发送配置
  mail:
    host: smtp.163.com
    port: 465
    username: 17771873239@163.com
    password: EFuvHFv7XA6S9xsP
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
baidu:
  translate:
    app-id: 20260810002663166
    security-key: sOxY9A_3TSxHwNNN0b6p
# 第三方服务 API 配置
search-api:
  api-key: ZbZK7yBvk3Ls39kuGrED3tsg

